version: "3"

# mongo-service
mongo-service:
  container_name: mongo-service
  image: mongo:latest
  restart: always
  networks:
    - net
  volumes:
    - ./data:/data/db
  ports:
    - "27017:27017"
# pulse-service
pulse-service:
  container_name: pulse-service
  build: ./pulse-service
  restart: always
  ports:
    - "8000:8000"
  expose:
    - 8000
  networks:
    - net
# networks
networks:
  network1:
    driver: bridge
