version: "3"

services:
  # mongodb-service
  mongodb-service:
    container_name: mongodb-service
    image: mongo:latest
    restart: always
    networks:
      - network1
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  # pulse-service
  pulse-service:
    container_name: pulse-service
    build: ./pulse-service
    restart: always
    ports:
      - "8000:8000"
    expose:
      - 8000
    networks:
      - network1
    volumes:
      - ./storage:/data/storage:ro
    depends_on:
      - mongodb-service
  # ui-service
  ui-service:
    container_name: ui-service
    build: ./front
    restart: always
    ports:
      - "3000:3000"
    expose:
      - 3000
    networks:
      - network1
    volumes:
      - ./storage:/data/storage:ro
    depends_on:
      - pulse-service
networks:
  network1:
    driver: bridge
