server:
  port: 8000

storagePath: "./files/"

---
storagePath: "/home/putin/pulse/storage"

spring:
  config:
    activate:
      on-profile: cloud
  data:
    mongodb:
      host: mongodb-service
      port: 27017
      database: pulse

---
storagePath: ".\\files\\"

spring:
  config:
    activate:
      on-profile: develop
  data:
    mongodb:
      host: localhost
      port: 27017
      database: pulse
